### ISSUE TITLE
eom build failture with USE="dbus gtk3"

### ISSUE THREAD

**Issue by ghost** [necrose99/necromancy-overlay#13]
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../lib64/libcairo.so: undefined reference to symbol 'XUnlockDisplay'
/usr/lib64/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:751: recipe for target 'eom' failed
make[3]: **\* [eom] Error 1

**Comment by necrose99** [comment]
I have no ebuild of reference some were recent rescues.
