### ISSUE TITLE
repoman needs be run on this mess.

### ISSUE THREAD

**Issue by necrose99** [necrose99/necromancy-overlay#3]
note to self : need to run repoman to generate manifests etc, QA checks etc. changelogs 
then i can test some of my hacked up ebuild's , then push upstream perhaps .... 
hard drive is alive but need to seriously get my 5TB external unpacked  <<<< Dying 2nd HDD as image 
then get a new 2nd laptop drive on order ....  
1000 mile moves kinda killed the bank... 

note to self need to file bug soon with Gentoo overlays after QA +++ is a bit more than fuggly 
so will be officially on layman via gpo zugania 

also need to make a Sabayon-labs-overlay in shared org ... for more official userland packages .

**Comment by fusion809** [comment]
I would be willing to help with that, if I could, but I haven't the foggiest what "repoman" even is...

**Comment by necrose99** [comment]
https://devmanual.gentoo.org/general-concepts/manifest/
https://raw.githubusercontent.com/necrose99/necromancy-overlay/master/scripts/repomanz.sh
https://wiki.gentoo.org/wiki/Repoman

### add most repoman fuctions into a shell that should take care of the repo.

#### since I am new @ repoman I figured best to script many of the use cases....

## and a few extra uses for those more stuborn ebuilds....

## now if I could only make a Metagen recursive script...  for xmls

repoman fix
repoman manifest
repoman full
repoman commit
repoman -m "Version bump" commit

**yes We need a 'PADAWAN' Dev manual** , **Tinkerer/User/s friendly *_, Dev manual less you start to rip apart ebuild's of others it can be frustrating to connect the dot...s  to the devmanual 
*_I swear it reads like Swahili ... **
and i'm **dyslexic** so i'm really tolerant of formatting spelling errors etc. 
you dont get Jedi Gentoo devs in a flash.... the dev manual takes months...... years for a novice... 
**can give your self a virtual lobotomy trying to decipher** it at times, then some times looking an an ebuild weeks latter the light-bulb clicks, other times its still irritating.... 
**something that is more novice friendly has long since been neaded**, some packages if users were **trained could help the devs keep maintained.** thus freeing up devs for more **serious issues** or **difficult packages.**
yes An step by step guide for different types needs to be wiki'd   old ebuild absconded for a template and how you can plug in depends change the name to fit package , make the change log file manifests cross fingers see if it builds... , test more and make it a production ebuild... 
*_Frag lots of mobs in Game to vent unholy amounts of wrath stacks .... *_ let the hamster wheels in the brain cool, then aha.... moments...  then when the fix pops up plug it in... after irritation subsides... 
*_then Gentoo/Funtoo/Pentoo /Sabayon packages... Cheers !!! *_
