### ISSUE TITLE
thefuck

### ISSUE THREAD

**Issue by necrose99** [necrose99/necromancy-overlay#5]
https://github.com/nvbn/thefuck

**Comment by necrose99** [comment]
cannibalizing Yara-python  Skeleton

**Comment by blshkv** [comment]
I say no to this tool. See "https://github.com/pentoo/pentoo-historical/issues/350" for details

**Comment by necrose99** [comment]
ok it will burn , mainly a training ebuild , I Likely will fix it then wont bother to update it. 
mainly for tinkering
